"""init schema

Revision ID: 34d118ecbe69
Revises: 
Create Date: 2025-08-16 17:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '34d118ecbe69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjust as needed ###
    op.create_table(
        'incidents',
        sa.Column('id', sa.Integer, primary_key=True, index=True),
        sa.Column('src_ip', sa.String, nullable=False),
        sa.Column('dst', sa.String),
        sa.Column('vector', sa.String),
        sa.Column('bytes', sa.Integer),
        sa.Column('requests', sa.Integer),
        sa.Column('score', sa.Float),
        sa.Column('level', sa.String),
        sa.Column('country', sa.String),
        sa.Column('lat', sa.Float),
        sa.Column('lon', sa.Float),
        sa.Column('details', sa.String),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table('incidents')
